name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout git repository
        uses: actions/checkout@v2.3.1
      - name: setup golang
        uses: actions/setup-go@v2
        with:
          go-version: "^1.15"
      - name: go fmt
        run: go fmt ./...
      - name: go vet
        run: go vet ./...
      - name: go test
        run: go test ./...

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout git repository
        uses: actions/checkout@v2.3.1
      - name: setup golang
        uses: actions/setup-go@v2
        with:
          go-version: "^1.15"
      - name: build windows binary
        run: GOOS=windows GOARCH=amd64 go build -ldflags "-s -w" -o updater.exe
      - name: upload binary
        uses: actions/upload-artifact@v2
        with:
          name: updater
          path: updater.exe
