name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout git repository
        uses: actions/checkout@v2.3.1
      - name: setup golang
        uses: actions/setup-go@v2
        with:
          go-version: "^1.15"
      - name: build windows binary
        run: GOOS=windows GOARCH=amd64 go build -o updater.exe
      - uses: actions/upload-artifact@v2
        with:
          name: updater
          path: updater.exe
